create table if not exists promoted_cities (
  id bigint generated by default as identity primary key,
  city_code text not null,
  flight_id bigint,
  promoted_at timestamptz default now(),
  generated_content text
);

create index idx_promoted_cities_city_code on promoted_cities(city_code);
create index idx_promoted_cities_promoted_at on promoted_cities(promoted_at);
