create table if not exists public.recommendation_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  city text not null,
  region text not null,
  price integer not null,
  recommendation_type text not null, -- 'deal', 'rotation', 'discovery'
  departure_date date,
  return_date date,
  airline text
);

-- Add RLS policies
alter table public.recommendation_history enable row level security;

create policy "Enable read access for all users"
  on public.recommendation_history for select
  using (true);

create policy "Enable insert access for service role only"
  on public.recommendation_history for insert
  with check (true);
